#!/bin/bash

IFS=- read mc_version jre_version <<< $DOCKER_TAG

paper_version=$(curl -L https://papermc.io/api/v1/paper/$mc_version/latest | sed -E -e 's/^.*"build":"([0-9]+)"$/\1/')

docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg PAPER_VERSION="$paper_version" \
             --build-arg MC_VERSION="$mc_version" \
             --build-arg JRE_VERSION="$jre_version" \
             -t $IMAGE_NAME .
